# NumPy == numeric Python

www.numpy.org

ndarray = represents an N-dimensional array (== tensor)

* N==0 scalar
* N==1 vector
* N==2 matrix
* N== ....


In [2]:
import numpy as np

# Whetting your appetite
Numpy makes calculations **really fast**.

In [3]:
n = 10_000
# sum of squares of 0, 1, 2, ..., n-1
%timeit sum([i**2 for i in range(n)])
%timeit ( np.arange(n)**2 ).sum()

26.9 ms ± 5.51 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
313 µs ± 82.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [4]:
def variance(x):
    n = len(x)
    mean = sum(x) / n
    
    sum_sq = 0
    for i in range(n):
        sum_sq += (x[i]-mean)**2
    
    return sum_sq/(n-1)

In [5]:
variance([0, 0, 0, 0, 0]), variance([1, 2, 3, 4])

(0.0, 1.6666666666666667)

In [6]:
np.random.seed(123)
x = np.random.rand(10_000)

In [7]:
%timeit variance(x)
%timeit x.var(ddof=1)
%timeit ((x - x.mean())**2).sum()/(len(x) - 1)

85.9 ms ± 8.07 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
486 µs ± 97.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
479 µs ± 69.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


---
# Loading Arrays

- `np.load(file, mmap_mode=None, allow_pickle=False, fix_imports=True, encoding='ASCII')`
- `np.loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes', max_rows=None)`

In [8]:
a = np.loadtxt('data/a.txt')
print(type(a))
print(a)

<class 'numpy.ndarray'>
[0.86077448 0.59449515 0.2448484  0.36079936 0.34046729 0.48255381
 0.72563607 0.43003229 0.15350375 0.24524989 0.92316945 0.86258945
 0.8456167  0.0601834  0.03900676]


In [9]:
a = np.load('data/a.npy')
print(type(a))
print(a)

<class 'numpy.ndarray'>
[0.86077448 0.59449515 0.2448484  0.36079936 0.34046729 0.48255381
 0.72563607 0.43003229 0.15350375 0.24524989 0.92316945 0.86258945
 0.8456167  0.0601834  0.03900676]


In [10]:
arrays = np.load('data/a.npz')
print(type(arrays))
print(arrays.files)

<class 'numpy.lib.npyio.NpzFile'>
['arr_0', 'arr_1']


In [11]:
a = arrays['arr_0']
b = arrays['arr_1']
print(type(a))
print(a)
print(type(b))
print(b)

<class 'numpy.ndarray'>
[0.86077448 0.59449515 0.2448484  0.36079936 0.34046729 0.48255381
 0.72563607 0.43003229 0.15350375 0.24524989 0.92316945 0.86258945
 0.8456167  0.0601834  0.03900676]
<class 'numpy.ndarray'>
[0.17583129 0.33737294 0.62612302 0.20691698 0.88523754 0.52178992
 0.76665624 0.70404154 0.82148591 0.88617062]


---
# Saving Arrays

- `np.savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='n', header='', footer='', comments='# ', encoding=None)`
- `np.savez(file, *args, **kwds)`
- `np.save(file, arr, allow_pickle=True, fix_imports=True)`

In [12]:
np.savetxt('data/new_a.txt', a)
np.save('data/new_a.npy', a)

In [13]:
np.savez('data/new_a.npz', a, b)
check = np.load('data/new_a.npz')
print(check.files)

['arr_0', 'arr_1']


In [14]:
np.savez('data/new_a.npz', my_a_array=a, some_weird_name=b)
check = np.load('data/new_a.npz')
print(check.files)
print(check['some_weird_name'])

['my_a_array', 'some_weird_name']
[0.17583129 0.33737294 0.62612302 0.20691698 0.88523754 0.52178992
 0.76665624 0.70404154 0.82148591 0.88617062]


---
# Creating Arrays
A numpy array is similar to a Python list but contains only data of the same type. E.g. only floats, or only dictionaries. Python lists on the other hand allow for different types in the same list.

---
## from built-in functions

- `np.arange([start, ]stop, [step, ]dtype=None)`
- `np.zeros(shape, dtype=float, order='C')`
- `np.ones(shape, dtype=float, order='C')`
- `np.empty(shape, dtype=float, order='C')`
- `np.full(shape, fillvalue, dtype=float, order='C')`
---

*np.arange* is similar to *range* for lists.  
With only __one argument__ *N* an array is created from 0 to the *N - 1*.

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

With __two arguments__ *N* and *M* an array is created that starts with *N* and ends with *M - 1*.

In [16]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

With __three arguments__ *N*, *M*, and *L* an array is created that starts *N*, ends with *M - 1* and takes steps of size *L* in between.

In [17]:
np.arange(3, 11, 2)

array([3, 5, 7, 9])

With __dtype__ the type of stored data can be specified.

In [18]:
np.arange(10, dtype=np.float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [19]:
np.arange(10.0)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [20]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [21]:
np.ones(3)

array([1., 1., 1.])

In [22]:
np.empty(5)

array([1.5932131e-316, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
       2.3715151e-322])

In [23]:
np.full(3, 9.3)

array([9.3, 9.3, 9.3])

---
## from lists

- `np.array(list)`
    
If not all elements in the list have the same type numpy automatically converts the data to a common type, if possible. If not it will be an 'object' type.

---

In [24]:
mylist = [1, 4, 2, 290]
np.array(mylist)

array([  1,   4,   2, 290])

Here we use integers and a string in the list. This is converted to all strings.

In [25]:
mylist = [1, 4, 'a', 290]
np.array(mylist)

array(['1', '4', 'a', '290'], dtype='<U21')

Now we use an integer, a string and a dictionary. This is all converted to dtype object.

In [26]:
mylist = [1, 'a', {'b':4}]
np.array(mylist)

array([1, 'a', {'b': 4}], dtype=object)

---
## from other arrays

- `np.empty_like(a, dtype=None, order='K', subok=True, shape=None)`
- `np.full_like(a, fill_value, dtype=None, order='K', subok=True, shape=None)`
- `np.zeros_like(a, dtype=None, order='K', subok=True, shape=None)`
- `np.ones_like(a, dtype=None, order='K', subok=True, shape=None)`
    
order is a memory layout keyword and subok is a keyword specifying the (sub)-class. I haven't used either one.

---

In [27]:
x = np.arange(10)
np.empty_like(x)

array([                  0, 8462656716707034229, 7311068618034541413,
       2466321603649696626, 7017771692297694773, 3544388029326189940,
       6068092717742697785, 4049644503005016113, 6500154650853258542,
           140435332824354])

In [28]:
np.full_like(x, 0.3)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
np.full_like(x, 1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [30]:
np.full_like(x, 0.3, dtype=np.float)

array([0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3])

In [31]:
np.zeros_like(x, shape=(3, 6))

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

---
# Array properties and methods

- Properties
    - ndim
    - shape
    - size
    - T
    ...
- Methods
    - max
    - min
    - mean
    - reshape
    - sort
    - flatten
    - tolist
    - swapaxes ...
    
There are many more properties and methods that you can look up in the documentation.

---

In [32]:
x = np.array([3, 6, 0, 9.2 , 0.55, 12, 4.3, 6, 100, -23, -4.33, 0])
print('ndim = ', x.ndim)
print('shape = ', x.shape)
print('size = ', x.size)
print(x)

ndim =  1
shape =  (12,)
size =  12
[  3.     6.     0.     9.2    0.55  12.     4.3    6.   100.   -23.
  -4.33   0.  ]


In [33]:
print('max = ', x.max())
print('min =', x.min())
print('mean = ', x.mean())

max =  100.0
min = -23.0
mean =  9.476666666666668


In [34]:
x = x.reshape((2, 6))
print('ndim = ', x.ndim)
print('shape = ', x.shape)
print('size = ', x.size)
print(x)
x.sort(axis=0)
print(x)
x.sort(axis=1)
print(x)

ndim =  2
shape =  (2, 6)
size =  12
[[  3.     6.     0.     9.2    0.55  12.  ]
 [  4.3    6.   100.   -23.    -4.33   0.  ]]
[[  3.     6.     0.   -23.    -4.33   0.  ]
 [  4.3    6.   100.     9.2    0.55  12.  ]]
[[-23.    -4.33   0.     0.     3.     6.  ]
 [  0.55   4.3    6.     9.2   12.   100.  ]]


_Note_

- Sort changes the array that it works on.
- Reshape does __not__ change the array it works on.

---
Like always in Python we can string methods together.

In [35]:
print(x.tolist())
print(x.flatten().tolist())

[[-23.0, -4.33, 0.0, 0.0, 3.0, 6.0], [0.55, 4.3, 6.0, 9.2, 12.0, 100.0]]
[-23.0, -4.33, 0.0, 0.0, 3.0, 6.0, 0.55, 4.3, 6.0, 9.2, 12.0, 100.0]


In [37]:
print("here comes x")
print(x)
print("here comes x.reshape(6, 2)")
print(x.reshape(6, 2))
print("here comes x.swapaxes(0, 1)")
print(x.swapaxes(0, 1))
print("here comes x.T")
print(x.T)

here comes x
[[-23.    -4.33   0.     0.     3.     6.  ]
 [  0.55   4.3    6.     9.2   12.   100.  ]]
here comes x.reshape(6, 2)
[[-23.    -4.33]
 [  0.     0.  ]
 [  3.     6.  ]
 [  0.55   4.3 ]
 [  6.     9.2 ]
 [ 12.   100.  ]]
here comes x.swapaxes(0, 1)
[[-23.     0.55]
 [ -4.33   4.3 ]
 [  0.     6.  ]
 [  0.     9.2 ]
 [  3.    12.  ]
 [  6.   100.  ]]
here comes x.T
[[-23.     0.55]
 [ -4.33   4.3 ]
 [  0.     6.  ]
 [  0.     9.2 ]
 [  3.    12.  ]
 [  6.   100.  ]]


*Note*: reshape and swapaxes are not identical! Swapaxes is identical to transpose (T) if we have an array with two axes.

---
# 1. Exercise

You are working for a company that monitors the weather in Berlin. The company has collected data on temperature at one specific location.
The data is stored in the file 'data.npz'. Each array in the file represents one day.
1. Create __one__ array that holds all temperatures of all days such that the data of one day is in one column.
2. Create __one__ array that holds all temperatures of all days such that the data of one day is in one row.
3. Print out __neatly__
    - The minimum and maximum temperature for each day.
    - The mean temperature for each day.
    - The minimum, maximum and mean temperature for all three days.
4. Order the temperatures of each day and generate a list of the highest temperature and one with the lowest temperature of each day.
5. Save the results of 4 into __one__ file and give the arrays the names 'maximum' and 'minimum' in the file.

# Slicing and Dicing

Just like with lists elements of numpy arrays can be addressed individually or collectively.
- the index of the element is given in brackets
- the indexes are given as slices
- the indexes are given as an array

In [38]:
x = np.arange(20)
print(x)
y = np.arange(20).reshape(4,5)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


A simple index works just like with lists. For arrays the indexes are separated by a comma. The first index refers to the row and the second refers to the column.

In [39]:
print(x[-2], x[10])
print(y[-1,-2], y[2,0])

18 10
18 10


Slices work like `[start:stop[:step]]` where start and stop are mandatory and step is optional.

In [40]:
print(x[1:5])
print(y[1:3, 2:5:2])

[1 2 3 4]
[[ 7  9]
 [12 14]]


Slices can also be used to reverse the order.

In [41]:
print(x[12:4: -2])
print(y[::-2, 2])

[12 10  8  6]
[17  7]


Here we use index arrays with integers.

In [42]:
idx1 = np.array([4, 8, 5, -3, 10])
idx2 = np.array([-1, 2])
idx3 = np.array([2, 1])
print(x[idx1])
print(y[idx2, idx3])

[ 4  8  5 17 10]
[17 11]


Now we use an index array with booleans. A combination of booleans, slices and integers is also possible.

In [43]:
T = True
F = False
idx1 = np.array([F, F, T, T, F, F, F, T, F, T, T, T, F, F, T, T, F, F, F, T])
idx2 = np.array([F, F, T, T])
idx3 = np.array([0, 2])
print(x[idx1])
print(y[idx2, idx3])

[ 2  3  7  9 10 11 14 15 19]
[10 17]


We can also get rows or columns.

In [44]:
print(y[3])  # the fourth row
print(y[2, :])  # the third row
print(y[:, 0])  # the first column

[15 16 17 18 19]
[10 11 12 13 14]
[ 0  5 10 15]


# Comparison and Arithmetic

The comparison or the arithmetic on arrays is done elementwise. Here are some examples.

In [45]:
x = np.arange(10)
y = np.arange(10)
print(x + y)
print(x / 3)
print(x > y)
print(x == y)

[ 0  2  4  6  8 10 12 14 16 18]
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.        ]
[False False False False False False False False False False]
[ True  True  True  True  True  True  True  True  True  True]


In [46]:
print(2 < 3 < 5)
print(2 < x)
print(x < 5)

True
[False False False  True  True  True  True  True  True  True]
[ True  True  True  True  True False False False False False]


In [47]:
try:
    print(2 < x < 5)
except:
    print('that did not work')
try:
    print(2 < x & x < 5)
except:
    print('that did not work again')
try:
    print((2 < x) & (x < 5))
except:
    print('AGAIN ????')

that did not work
that did not work again
[False False False  True  True False False False False False]


In [48]:
try:
    print((2 < x < 5).any())
except:
    print('that did not work')
try:
    print((2 < x & x < 5)).all()
except:
    print('that did not work again')
try:
    print((2 < x).any() & (x < 5).all())
except:
    print('AGAIN ????')

that did not work
that did not work again
False


# Broadcasting
In general, arrays must have identical shapes for arithmetic.

In [49]:
try:
    np.arange(10) * np.arange(5)
except:
    print("no that doesn't work")

no that doesn't work


However, there is something called broadcasting. Broadcasting is very powerful but maybe not immediatly intuitive. Let's start with a very simple example. Multiplication of a scalar with an array.

In [51]:
x = np.arange(8)
y = np.arange(8).reshape(2, 4)
z = np.arange(8).reshape(4, 2)
print("x and x * 2")
print(x)
print(x * 2)
print("\ny and y * 3")
print(y)
print(y * 3)
print("\nz and z * 4")
print(z)
print(z * 4)

x and x * 2
[0 1 2 3 4 5 6 7]
[ 0  2  4  6  8 10 12 14]

y and y * 3
[[0 1 2 3]
 [4 5 6 7]]
[[ 0  3  6  9]
 [12 15 18 21]]

z and z * 4
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[ 0  4]
 [ 8 12]
 [16 20]
 [24 28]]


Now let's try to multiply these arrays with the vector np.array([2, 3]) and see what happens.

In [53]:
a = np.array([2,3])
print("a and a.shape", a, a.shape)
print("\nx * a:")
try:
    print(x * a)
except:
    print('x * a does not work')
print("\ny * a:")
try:
    print(y * a)
except:
    print('y * a does not work')
print("\nz * a:")
try:
    print(z * a)
except:
    print('z * a does not work')

a and a.shape [2 3] (2,)

x * a:
x * a does not work

y * a:
y * a does not work

z * a:
[[ 0  3]
 [ 4  9]
 [ 8 15]
 [12 21]]


And now let's reshape the vector.

In [55]:
a = np.array([2,3]).reshape(2,1)
print("a and a.shape", a, a.shape)
print("\nx * a:")
try:
    print(x * a)
except:
    print('x * a does not work')
print("\ny * a:")
try:
    print(y * a)
except:
    print('y * a does not work')
print("\nz * a:")
try:
    print(z * a)
except:
    print('z * a does not work')

a and a.shape [[2]
 [3]] (2, 1)

x * a:
[[ 0  2  4  6  8 10 12 14]
 [ 0  3  6  9 12 15 18 21]]

y * a:
[[ 0  2  4  6]
 [12 15 18 21]]

z * a:
z * a does not work


# 2. Exercise

Use the data from the previous exercise.

- Print out __neatly__ the temperatures at 3pm on Monday, 10am on Tuesday and 6pm on Wednesday.
- Print out the temperatures at 2pm and at 10am of each day and in that order.
- Print out the temperatures of every third hour starting at 10pm and ending at 9am on Wednesday.
- Print out all temperatures that are below 18.
- The temperatures are in Celsius. Convert them to Farenheit (°F = °C × 1.8 + 32)
- And just for the sake of practicing divide the temparatures of Monday by 2, of Tuesday by 3 and of Wednesday by 4.

# Useful Functions

- mathematical functions like `np.sin`, `np.exp`, `np.log` ... [numpy doc](<https://docs.scipy.org/doc/numpy/reference/routines.math.html>)
- linear algebra like eigenvectors and -values, inverse and norm ... [scipy doc](<https://docs.scipy.org/doc/numpy/reference/routines.linalg.html>)
- matrix and vector multiplication
- logical functions like `np.where`, `np.argwhere`, `np.nonzero`
- random numbers like `np.random.randn`, `np.random.randint`, `np.random.choice` ...

In [56]:
from scipy import linalg
x = np.arange(3)
y = np.arange(3,6)
z = np.arange(6, 15).reshape(3,3)
print('here comes x: ', x)
print('here comes y: ', y)
print('here comes z: ')
print(z)
print('here comes the sin of x: ', np.sin(x))
print('here comes the log of x + 1: ', np.log(x + 1))
print('here comes the norm of x: ', linalg.norm(x))

here comes x:  [0 1 2]
here comes y:  [3 4 5]
here comes z: 
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
here comes the sin of x:  [0.         0.84147098 0.90929743]
here comes the log of x + 1:  [0.         0.69314718 1.09861229]
here comes the norm of x:  2.23606797749979


In [57]:
print('here comes the identity matrix: ')
print(np.eye(3))
print('here comes the product of x and y: ', x @ y)
print('here comes the product of x and z: ', x @ z)
print('here comes the product of x, z, and y: ', x @ z @ y)
print('here comes the product of z and z: ')
print(z @ z)

here comes the identity matrix: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
here comes the product of x and y:  14
here comes the product of x and z:  [33 36 39]
here comes the product of x, z, and y:  438
here comes the product of z and z: 
[[195 216 237]
 [276 306 336]
 [357 396 435]]


In [58]:
print(np.where(z > 10))
print(np.argwhere(z > 10))
print(np.where(z > 10, z, 10 * z))

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))
[[1 2]
 [2 0]
 [2 1]
 [2 2]]
[[ 60  70  80]
 [ 90 100  11]
 [ 12  13  14]]


In [59]:
print(np.nonzero(z))
print(np.flatnonzero(z))

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))
[0 1 2 3 4 5 6 7 8]


In [61]:
print('np.random.choice(x) chooses a random element in x: ', np.random.choice(x))
print('np.random.randint(5) chooses a random integer from 0 to 4: ', np.random.randint(5))
print('np.random.randint(5, 16) chooses a random integer from 5 to 15: ', np.random.randint(5, 16))
print('np.random.randn() chooses a random float from a normal distribution: ', np.random.randn())
print('np.random.randn(2, 3, 4) chooses random floats in an array from a normal distribution: ')
print(np.random.randn(2, 3, 4))

np.random.choice(x) chooses a random element in x:  1
np.random.randint(5) chooses a random integer from 0 to 4:  2
np.random.randint(5, 16) chooses a random integer from 5 to 15:  15
np.random.randn() chooses a random float from a normal distribution:  0.3771137178539186
np.random.randn(2, 3, 4) chooses random floats in an array from a normal distribution: 
[[[-0.9915795  -0.94367527  1.60898888  0.31828661]
  [ 0.05893849  0.38069425  0.54869711 -0.50130167]
  [-1.41609521  1.25577497  0.25417228  0.83392561]]

 [[-0.91920306  0.34203327 -1.93782253 -0.80602036]
  [-0.16721394 -0.09519763  1.30942981 -1.44199699]
  [-0.11725418  0.26042864  1.02241203 -1.77891872]]]


# Axes and Dimensions

- 1 axis -> vector
- 2 axes -> matrix
- 3+ axes -> tensor

along each axis we call the number of entries the dimension

- a vector with 10 entries is 10-dimensional
- a matrix with dimension 2 and 3 has two rows and three columns
- similar for tensors

In [63]:
a = np.ones((1,2,3))
b = np.ones((2,3,1))
c = np.ones((3,1,2))
d = np.arange(4, 7)
print("shapes and values of a, b, c, and d")
print("\nhere comes a: ", a.shape)
print(a)
print("\nhere comes b: ", b.shape)
print(b)
print("\nhere comes c: ", c.shape)
print(c)
print("\nhere comes d: ", d.shape)
print(d)

shapes and values of a, b, c, and d

here comes a:  (1, 2, 3)
[[[1. 1. 1.]
  [1. 1. 1.]]]

here comes b:  (2, 3, 1)
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]]

here comes c:  (3, 1, 2)
[[[1. 1.]]

 [[1. 1.]]

 [[1. 1.]]]

here comes d:  (3,)
[4 5 6]


Please note the difference between b and c! How many axes does every array have and what are the dimensions?

# Matrix Multiplication

Given two vectors/matrices/tensors __A__ and __B__ we define a matrix multiplication also called __dot product__ as

$$ A \cdot B = \sum_i^n A_i \cdot B_i $$

Note that this is different from an elementwise multiplication of vectors/matrices/tensors.

$$ A \star B = A_i \cdot B_i $$

In the cells below there are a variety of different multiplications, both matrix and elementwise.

In [67]:
# broad casting
print("a * d: ", (a * d).shape)
print("d * a: ", (d * a).shape)
print("b * d: ", (b * d).shape)
print("d * b: ", (d * b).shape)
try:
    print("c * d: ", (c * d).shape)
except:
    print("c * d doesn't work")
try:
    print("d * c: ", (d * c).shape)
except:
    print("d * c doesn't work")

a * d:  (1, 2, 3)
d * a:  (1, 2, 3)
b * d:  (2, 3, 3)
d * b:  (2, 3, 3)
c * d doesn't work
d * c doesn't work


In [69]:
print('shape a: ', a.shape)
print('shape b: ', b.shape)
print('shape c: ', c.shape)
print('shape d: ', d.shape)
print('\na dot d:')
try:
    x = np.dot(a, d)
    print(x.shape)
    print(x)
except:
    print("a dot d doesn't work!")
print('\nd dot a:')
try:
    x = np.dot(d, a)
    print(x.shape)
    print(x)
except:
    print("d dot a doesn't work!")
print('\na dot b:')
try:
    x = np.dot(b, d)
    print(x.shape)
    print(x)
except:
    print("b dot d doesn't work!")
print('\nd dot b:')
try:
    x = np.dot(d, b)
    print(x.shape)
    print(x)
except:
    print("d dot b doesn't work!")
print('\nc dot d:')
try:
    x = np.dot(c, d)
    print(x.shape)
    print(x)
except:
    print("c dot d doesn't work!")
print('\nd dot c:')
try:
    x = np.dot(d, c)
    print(x.shape)
    print(x)
except:
    print("d dot c doesn't work!")
print('\na dot b:')
try:
    x = np.dot(a, b)
    print(x.shape)
    print(x)
except:
    print("a dot b doesn't work!")
print('\nb dot a:')
try:
    x = np.dot(b, a)
    print(x.shape)
    print(x)
except:
    print("b dot a doesn't work!")
print('\na dot c:')
try:
    x = np.dot(a, c)
    print(x.shape)
    print(x)
except:
    print("a dot c doesn't work!")
print('\nc dot a:')
try:
    x = np.dot(c, a)
    print(x.shape)
    print(x)
except:
    print("c dot a doesn't work!")
print('\nb dot c:')
try:
    x = np.dot(b, c)
    print(x.shape)
#    print(x)
except:
    print("b dot c doesn't work!")
print('\nc dot b:')
try:
    x = np.dot(c, b)
    print(x.shape)
    print(x)
except:
    print("c dot b doesn't work!")

shape a:  (1, 2, 3)
shape b:  (2, 3, 1)
shape c:  (3, 1, 2)
shape d:  (3,)

a dot d:
(1, 2)
[[15. 15.]]

d dot a:
d dot a doesn't work!

a dot b:
b dot d doesn't work!

d dot b:
(2, 1)
[[15.]
 [15.]]

c dot d:
c dot d doesn't work!

d dot c:
d dot c doesn't work!

a dot b:
(1, 2, 2, 1)
[[[[3.]
   [3.]]

  [[3.]
   [3.]]]]

b dot a:
b dot a doesn't work!

a dot c:
a dot c doesn't work!

c dot a:
(3, 1, 1, 3)
[[[[2. 2. 2.]]]


 [[[2. 2. 2.]]]


 [[[2. 2. 2.]]]]

b dot c:
(2, 3, 3, 2)

c dot b:
c dot b doesn't work!


# 3. Exercise

Check the results of the previous cell. Formulate for yourself a small paragraph (three to five sentences) that summarizes your findings. Try to use the words dimension and axis/axes as well as broadcasting and matrix multiplication.

# Tensor Product
There is a generalization of products to tensors. This is implemented in numpy's tensordot function.

`numpy.tensordot(a, b, axes=N)`

The argument 'axes' indicates over how many axes the summation runs. This affects the N last axes of tensor a and the first N axes of tensor b.

The special case of N = 0 is called the outer product. It means that there is no summation over any axis. Rather, every element of tensor a is multiplied with every element of b.

In [70]:
print(a.shape, b.shape, c.shape, d.shape)
# the outer product
print("\nresults for the outer product")
x = np.tensordot(d, d, axes=0)
print(x.shape)
x = np.tensordot(a, b, axes=0)
print(x.shape)

# the inner or dot product
print("\nresults for the inner product")
x = np.tensordot(d, d, axes=1)
print(x.shape)
x = np.tensordot(c, b, axes=1)
print(x.shape)

# the tensor product
print("\nresults for the tensor product")
x = np.tensordot(a, b, axes=2)
print(x.shape)
x = np.tensordot(a, a, axes=3)
print(x.shape)

(1, 2, 3) (2, 3, 1) (3, 1, 2) (3,)

results for the outer product
(3, 3)
(1, 2, 3, 2, 3, 1)

results for the inner product
()
(3, 1, 3, 1)

results for the tensor product
(1, 1)
()


# 4. Exercise

We denote the tensors a, b, and c as

$$ A = a_{i, j, k} \,\,\,\,\, B = b_{i, j, k} \,\,\,\,\, C = c_{i, j, k} $$

- Write down the equation for the outer product, the inner product and the tensor product.
- Write down a formula that gives the shape of a given tensor product?

There are two ways to calculate the tensor product between arbitrary axes.

In [71]:
x = np.tensordot(b, a, axes=([0, 2], [1, 0]))
print(x.shape)
print(a.shape)
y = np.swapaxes(a, 0, 1)
print(y.shape)

(3, 3)
(1, 2, 3)
(2, 1, 3)


In [72]:
# use swapaxes to make the following expressions work
x = np.tensordot(a, b, axes=1)
print(x.shape)

ValueError: shape-mismatch for sum

# 5. Exercise

In the final exercise we want to bring all the pieces together and take full advantage of what Numpy offers.

You are employed by a company that produces `N` types of cars. Each type of car comes in `M` different flavors. For each car and each flavor the company has factories in `L` different countries, each of which has a different VAT: from `0` to `L-1`% for the purchase of material. For each car and flavor there are 100 different materials needed.

`def car_production(material, cost_per_material, VAT)
    body
    return value`

1. Write a function that calculates the cost of production for 1 car and 1 flavor in 1 country. The function should be defined like above.  
2. Write a function that calculates the cost of production for `N` cars and 1 flavor in 1 country.
3. Write a function that calculates the cost of production for `N` cars and `M` flavors in 1 country.
4. Write a function that calculates the cost of production for `N` cars and `M` flavors in each of the `L` countries.

For this exercise assume you just know the cost of the material and choose these numbers randomly.